/*
 * LIMITED USE SOFTWARE LICENSE AGREEMENT
 *
 * This Limited Use Software License Agreement (the "Agreement") is a legal agreement between you, the end-user, and the AlgorithmicsAnonymous Team ("AlgorithmicsAnonymous"). By downloading or purchasing the software material, which includes source code (the "Source Code"), artwork data, music and software tools (collectively, the "Software"), you are agreeing to be bound by the terms of this Agreement. If you do not agree to the terms of this Agreement, promptly destroy the Software you may have downloaded or copied.
 *
 * AlgorithmicsAnonymous SOFTWARE LICENSE
 *
 * 1. Grant of License. AlgorithmicsAnonymous grants to you the right to use the Software. You have no ownership or proprietary rights in or to the Software, or the Trademark. For purposes of this section, "use" means loading the Software into RAM, as well as installation on a hard disk or other storage device. The Software, together with any archive copy thereof, shall be destroyed when no longer used in accordance with this Agreement, or when the right to use the Software is terminated. You agree that the Software will not be shipped, transferred or exported into any country in violation of the U.S. Export Administration Act (or any other law governing such matters) and that you will not utilize, in any other manner, the Software in violation of any applicable law.
 *
 * 2. Permitted Uses. For educational purposes only, you, the end-user, may use portions of the Source Code, such as particular routines, to develop your own software, but may not duplicate the Source Code, except as noted in paragraph 4. The limited right referenced in the preceding sentence is hereinafter referred to as "Educational Use." By so exercising the Educational Use right you shall not obtain any ownership, copyright, proprietary or other interest in or to the Source Code, or any portion of the Source Code. You may dispose of your own software in your sole discretion. With the exception of the Educational Use right, you may not otherwise use the Software, or an portion of the Software, which includes the Source Code, for commercial gain.
 *
 * 3. Prohibited Uses: Under no circumstances shall you, the end-user, be permitted, allowed or authorized to commercially exploit the Software. Neither you nor anyone at your direction shall do any of the following acts with regard to the Software, or any portion thereof:
 *
 * Rent;
 *
 * Sell;
 *
 * Lease;
 *
 * Offer on a pay-per-play basis;
 *
 * Distribute for money or any other consideration; or
 *
 * In any other manner and through any medium whatsoever commercially exploit or use for any commercial purpose.
 *
 * Notwithstanding the foregoing prohibitions, you may commercially exploit the software you develop by exercising the Educational Use right, referenced in paragraph 2. hereinabove.
 *
 * 4. Copyright. The Software and all copyrights related thereto (including all characters and other images generated by the Software or depicted in the Software) are owned by AlgorithmicsAnonymous and is protected by United States copyright laws and international treaty provisions. AlgorithmicsAnonymous shall retain exclusive ownership and copyright in and to the Software and all portions of the Software and you shall have no ownership or other proprietary interest in such materials. You must treat the Software like any other copyrighted material. You may not otherwise reproduce, copy or disclose to others, in whole or in any part, the Software. You may not copy the written materials accompanying the Software. You agree to use your best efforts to see that any user of the Software licensed hereunder complies with this Agreement.
 *
 * 5. NO WARRANTIES. AlgorithmicsAnonymous DISCLAIMS ALL WARRANTIES, BOTH EXPRESS IMPLIED, INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE WITH RESPECT TO THE SOFTWARE. THIS LIMITED WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS. YOU MAY HAVE OTHER RIGHTS WHICH VARY FROM JURISDICTION TO JURISDICTION. AlgorithmicsAnonymous DOES NOT WARRANT THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED, ERROR FREE OR MEET YOUR SPECIFIC REQUIREMENTS. THE WARRANTY SET FORTH ABOVE IS IN LIEU OF ALL OTHER EXPRESS WARRANTIES WHETHER ORAL OR WRITTEN. THE AGENTS, EMPLOYEES, DISTRIBUTORS, AND DEALERS OF AlgorithmicsAnonymous ARE NOT AUTHORIZED TO MAKE MODIFICATIONS TO THIS WARRANTY, OR ADDITIONAL WARRANTIES ON BEHALF OF AlgorithmicsAnonymous.
 *
 * Exclusive Remedies. The Software is being offered to you free of any charge. You agree that you have no remedy against AlgorithmicsAnonymous, its affiliates, contractors, suppliers, and agents for loss or damage caused by any defect or failure in the Software regardless of the form of action, whether in contract, tort, includinegligence, strict liability or otherwise, with regard to the Software. Copyright and other proprietary matters will be governed by United States laws and international treaties. IN ANY CASE, AlgorithmicsAnonymous SHALL NOT BE LIABLE FOR LOSS OF DATA, LOSS OF PROFITS, LOST SAVINGS, SPECIAL, INCIDENTAL, CONSEQUENTIAL, INDIRECT OR OTHER SIMILAR DAMAGES ARISING FROM BREACH OF WARRANTY, BREACH OF CONTRACT, NEGLIGENCE, OR OTHER LEGAL THEORY EVEN IF AlgorithmicsAnonymous OR ITS AGENT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY. Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.
 */

package com.sandvoxel.generitech.common.config;

import com.sandvoxel.generitech.api.util.EnumOreType;
import com.sandvoxel.generitech.common.util.ConfigHelper;
import com.sandvoxel.generitech.common.util.EnumOres;
import com.sandvoxel.generitech.common.util.LogHelper;
import com.sandvoxel.generitech.common.world.WorldGen;
import net.minecraft.world.biome.Biome;
import net.minecraftforge.common.config.Configuration;

import java.util.HashMap;
import java.util.Map;

public class ConfigWorldGen {
    public static final Map<EnumOres, OreConfig> OreGenConfig = new HashMap<>(EnumOres.values().length);
    private static final Map<EnumOres, OreConfig> OreGenConfigDefaults = new HashMap<>(EnumOres.values().length);
    private static final int[] DEFAULT_DIMENSION_BLACKLIST = {-1, 1};

    static {
        for (EnumOres ore : EnumOres.byType(EnumOreType.ORE)) {
            OreConfig defaultConf = new OreConfig();
            defaultConf.Enabled = true;
            defaultConf.DimensionRestriction = RestrictionType.Blacklist;
            defaultConf.Dimensions = DEFAULT_DIMENSION_BLACKLIST;
            defaultConf.BiomeRestriction = RestrictionType.Blacklist;
            defaultConf.Biomes = new String[]{};

            defaultConf.ChunkOccurrence = 20;

            switch (ore) {
                case COPPER:
                    defaultConf.MinY = 10;
                    defaultConf.MaxY = 75;
                    defaultConf.MinVeinSize = 13;
                    defaultConf.MaxVeinSize = 19;
                    defaultConf.Weight = 40;
                    break;

                case TIN:
                    defaultConf.MinY = 20;
                    defaultConf.MaxY = 55;
                    defaultConf.MinVeinSize = 7;
                    defaultConf.MaxVeinSize = 13;
                    defaultConf.Weight = 40;
                    break;

                case LEAD:
                    defaultConf.MinY = 10;
                    defaultConf.MaxY = 35;
                    defaultConf.MinVeinSize = 5;
                    defaultConf.MaxVeinSize = 11;
                    defaultConf.Weight = 20;
                    break;

                default:
                    defaultConf.MaxY = 65;
                    defaultConf.MinY = 5;
                    defaultConf.MinVeinSize = 3;
                    defaultConf.MaxVeinSize = 10;
                    defaultConf.Weight = 20;
                    break;

            }

            OreGenConfigDefaults.put(ore, defaultConf);

        }
    }

    public static void init(Configuration config) {
        config.setCategoryLanguageKey(Config.Category.WORLDGEN, "config.worldgen");
        config.setCategoryRequiresWorldRestart(Config.Category.WORLDGEN, false);

        final String WORLDGEN_ORE = Config.Category.WORLDGEN + ".ores";

        final String DESC_RETROGEN_ENABLED = "Enable retrogen in world";
        final String DESC_ENABLED = "Enable %s in world generation";
        final String DESC_MIN_Y = "Minimum Y level that %s will spawn at";
        final String DESC_MAX_Y = "Maximum Y level that %s will spawn at";
        final String DESC_MIN_VEIN_SIZE = "Min. number of %s ore in a vein";
        final String DESC_MAX_VEIN_SIZE = "Max. number of %s ore in a vein";
        final String DESC_WEIGHT = "Percent chance that %s will generate for each chunk occurrence";
        final String DESC_CHUNK_OCCURRENCE = "Number of times that %s will attempt to generate in each chunk";
        final String DESC_DIM_RESTRICTION_TYPE = "Dimension Restriction Type (Either 'blacklist' or 'whitelist')";
        final String DESC_DIM_RESTRICTION_LIST = "Dimension IDs to restrict ore spawning in";
        final String DESC_BIOME_RESTRICTION_TYPE = "Biome Restriction Type (Either 'blacklist' or 'whitelist')";
        final String DESC_BIOME_RESTRICTION_LIST = "Biome IDs to restrict ore spawning in";

        boolean retrogenEnabled = ConfigHelper.getBoolean(config, "Enable RetroGen", WORLDGEN_ORE, true, DESC_RETROGEN_ENABLED);
        WorldGen.setRetrogenEnabled(retrogenEnabled);

        for (EnumOres ore : EnumOres.byType(EnumOreType.ORE)) {
            String oreName = ore.getOreName();
            String oreNameLower = oreName.toLowerCase();
            String oreCategory = WORLDGEN_ORE + "." + oreName;
            OreConfig defaultConf = OreGenConfigDefaults.get(ore);

            OreConfig oreConf;

            oreConf = OreGenConfig.containsKey(ore) ? OreGenConfig.get(ore) : new OreConfig();

            oreConf.Enabled = ConfigHelper.getBoolean(config, String.format("Enable %s", oreName), WORLDGEN_ORE, defaultConf.Enabled, String.format(DESC_ENABLED, oreNameLower));

            oreConf.MinY = ConfigHelper.getInteger(config, "Min Y", oreCategory, defaultConf.MinY, String.format(DESC_MIN_Y, oreNameLower));
            oreConf.MaxY = ConfigHelper.getInteger(config, "Max Y", oreCategory, defaultConf.MaxY, String.format(DESC_MAX_Y, oreNameLower));
            if (oreConf.MinY >= oreConf.MaxY) {
                LogHelper.warn(String.format("%s Max Y must be greater than Min Y. Y Levels internally set to default. Please fix your config setting!", oreName));
                oreConf.MinY = defaultConf.MinY;
                oreConf.MaxY = defaultConf.MaxY;
            }

            oreConf.MinVeinSize = ConfigHelper.getInteger(config, "Min Vein Size", oreCategory, defaultConf.MinVeinSize, String.format(DESC_MIN_VEIN_SIZE, oreNameLower));
            oreConf.MaxVeinSize = ConfigHelper.getInteger(config, "Max Vein Size", oreCategory, defaultConf.MaxVeinSize, String.format(DESC_MAX_VEIN_SIZE, oreNameLower));
            if (oreConf.MinVeinSize >= oreConf.MaxVeinSize) {
                LogHelper.warn(String.format("%s Max Vein Size must be greater than Min Vein Size. Vein Sizes internally set to default. Please fix your config setting!", oreName));
                oreConf.MinVeinSize = defaultConf.MinVeinSize;
                oreConf.MaxVeinSize = defaultConf.MaxVeinSize;
            }

            oreConf.Weight = ConfigHelper.getInteger(config, "Weight", oreCategory, defaultConf.Weight, String.format(DESC_WEIGHT, oreNameLower));
            if (oreConf.Weight < 0) {
                LogHelper.warn(String.format("%s Weight must be greater than 0. Weight internally set to default. Please fix your config setting!", oreName));
                oreConf.Weight = defaultConf.Weight;
            }

            oreConf.ChunkOccurrence = ConfigHelper.getInteger(config, "ChunkOccurrence", oreCategory, defaultConf.ChunkOccurrence, String.format(DESC_CHUNK_OCCURRENCE, oreNameLower));
            if (oreConf.ChunkOccurrence < 0) {
                LogHelper.warn(String.format("%s ChunkOccurrence must be greater than 0. ChunkOccurrence internally set to default. Please fix your config setting!", oreName));
                oreConf.ChunkOccurrence = defaultConf.ChunkOccurrence;
            }

            String defaultDimRestriction = defaultConf.DimensionRestriction.name().toLowerCase();
            String dimensionRestriction = ConfigHelper.getString(config, "DimRestrictionType", oreCategory, defaultDimRestriction, DESC_DIM_RESTRICTION_TYPE);
            oreConf.DimensionRestriction = RestrictionType.fromString(dimensionRestriction, defaultConf.DimensionRestriction);

            oreConf.Dimensions = ConfigHelper.getIntegerList(config, "DimensionList", oreCategory, defaultConf.Dimensions, DESC_DIM_RESTRICTION_LIST);

            String defaultBiomeRestriction = defaultConf.BiomeRestriction.name().toLowerCase();
            String biomeRestriction = ConfigHelper.getString(config, "BiomeRestrictionType", oreCategory, defaultBiomeRestriction, DESC_BIOME_RESTRICTION_TYPE);
            oreConf.BiomeRestriction = RestrictionType.fromString(biomeRestriction, defaultConf.BiomeRestriction);

            oreConf.Biomes = ConfigHelper.getStringList(config, "BiomeList", oreCategory, defaultConf.Biomes, DESC_BIOME_RESTRICTION_LIST);

            OreGenConfig.put(ore, oreConf);
        }
    }

    public enum RestrictionType {
        Blacklist,
        Whitelist;

        public static RestrictionType fromString(String str, RestrictionType def) {
            for (RestrictionType rt : values()) {
                if (rt.name().equalsIgnoreCase(str)) {
                    return rt;
                }
            }

            return def;
        }
    }

    public static class OreConfig {
        public boolean Enabled;
        public int MinY;
        public int MaxY;
        public int MinVeinSize;
        public int MaxVeinSize;
        public int Weight;
        public int ChunkOccurrence;
        public RestrictionType DimensionRestriction;
        public int[] Dimensions;
        public RestrictionType BiomeRestriction;
        public String[] Biomes;

        public boolean isEnabledForDim(int dim) {
            boolean inList = false;
            for (int listDim : Dimensions)
                inList = inList || listDim == dim;
            return (inList && DimensionRestriction == RestrictionType.Whitelist) ||
                    (!inList && DimensionRestriction == RestrictionType.Blacklist);
        }

        public boolean isEnabledForBiome(Biome biome) {

            if (Biomes.length < 1)
                return true;

            boolean inList = false;
            for (String listBiome : Biomes) {
                if (inList) break;

                inList = listBiome == biome.getRegistryName().toString();
            }
            return (inList && BiomeRestriction == RestrictionType.Whitelist) ||
                    (!inList && BiomeRestriction == RestrictionType.Blacklist);
        }
    }
}
