/*
 * LIMITED USE SOFTWARE LICENSE AGREEMENT
 *
 * This Limited Use Software License Agreement (the "Agreement") is a legal agreement between you, the end-user, and the AlgorithmicsAnonymous Team ("AlgorithmicsAnonymous"). By downloading or purchasing the software material, which includes source code (the "Source Code"), artwork data, music and software tools (collectively, the "Software"), you are agreeing to be bound by the terms of this Agreement. If you do not agree to the terms of this Agreement, promptly destroy the Software you may have downloaded or copied.
 *
 * AlgorithmicsAnonymous SOFTWARE LICENSE
 *
 * 1. Grant of License. AlgorithmicsAnonymous grants to you the right to use the Software. You have no ownership or proprietary rights in or to the Software, or the Trademark. For purposes of this section, "use" means loading the Software into RAM, as well as installation on a hard disk or other storage device. The Software, together with any archive copy thereof, shall be destroyed when no longer used in accordance with this Agreement, or when the right to use the Software is terminated. You agree that the Software will not be shipped, transferred or exported into any country in violation of the U.S. Export Administration Act (or any other law governing such matters) and that you will not utilize, in any other manner, the Software in violation of any applicable law.
 *
 * 2. Permitted Uses. For educational purposes only, you, the end-user, may use portions of the Source Code, such as particular routines, to develop your own software, but may not duplicate the Source Code, except as noted in paragraph 4. The limited right referenced in the preceding sentence is hereinafter referred to as "Educational Use." By so exercising the Educational Use right you shall not obtain any ownership, copyright, proprietary or other interest in or to the Source Code, or any portion of the Source Code. You may dispose of your own software in your sole discretion. With the exception of the Educational Use right, you may not otherwise use the Software, or an portion of the Software, which includes the Source Code, for commercial gain.
 *
 * 3. Prohibited Uses: Under no circumstances shall you, the end-user, be permitted, allowed or authorized to commercially exploit the Software. Neither you nor anyone at your direction shall do any of the following acts with regard to the Software, or any portion thereof:
 *
 * Rent;
 *
 * Sell;
 *
 * Lease;
 *
 * Offer on a pay-per-play basis;
 *
 * Distribute for money or any other consideration; or
 *
 * In any other manner and through any medium whatsoever commercially exploit or use for any commercial purpose.
 *
 * Notwithstanding the foregoing prohibitions, you may commercially exploit the software you develop by exercising the Educational Use right, referenced in paragraph 2. hereinabove.
 *
 * 4. Copyright. The Software and all copyrights related thereto (including all characters and other images generated by the Software or depicted in the Software) are owned by AlgorithmicsAnonymous and is protected by United States copyright laws and international treaty provisions. AlgorithmicsAnonymous shall retain exclusive ownership and copyright in and to the Software and all portions of the Software and you shall have no ownership or other proprietary interest in such materials. You must treat the Software like any other copyrighted material. You may not otherwise reproduce, copy or disclose to others, in whole or in any part, the Software. You may not copy the written materials accompanying the Software. You agree to use your best efforts to see that any user of the Software licensed hereunder complies with this Agreement.
 *
 * 5. NO WARRANTIES. AlgorithmicsAnonymous DISCLAIMS ALL WARRANTIES, BOTH EXPRESS IMPLIED, INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE WITH RESPECT TO THE SOFTWARE. THIS LIMITED WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS. YOU MAY HAVE OTHER RIGHTS WHICH VARY FROM JURISDICTION TO JURISDICTION. AlgorithmicsAnonymous DOES NOT WARRANT THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED, ERROR FREE OR MEET YOUR SPECIFIC REQUIREMENTS. THE WARRANTY SET FORTH ABOVE IS IN LIEU OF ALL OTHER EXPRESS WARRANTIES WHETHER ORAL OR WRITTEN. THE AGENTS, EMPLOYEES, DISTRIBUTORS, AND DEALERS OF AlgorithmicsAnonymous ARE NOT AUTHORIZED TO MAKE MODIFICATIONS TO THIS WARRANTY, OR ADDITIONAL WARRANTIES ON BEHALF OF AlgorithmicsAnonymous.
 *
 * Exclusive Remedies. The Software is being offered to you free of any charge. You agree that you have no remedy against AlgorithmicsAnonymous, its affiliates, contractors, suppliers, and agents for loss or damage caused by any defect or failure in the Software regardless of the form of action, whether in contract, tort, includinegligence, strict liability or otherwise, with regard to the Software. Copyright and other proprietary matters will be governed by United States laws and international treaties. IN ANY CASE, AlgorithmicsAnonymous SHALL NOT BE LIABLE FOR LOSS OF DATA, LOSS OF PROFITS, LOST SAVINGS, SPECIAL, INCIDENTAL, CONSEQUENTIAL, INDIRECT OR OTHER SIMILAR DAMAGES ARISING FROM BREACH OF WARRANTY, BREACH OF CONTRACT, NEGLIGENCE, OR OTHER LEGAL THEORY EVEN IF AlgorithmicsAnonymous OR ITS AGENT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY. Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.
 */

package com.sandvoxel.generitech.common.world;

import com.google.common.collect.ArrayListMultimap;
import com.sandvoxel.generitech.Reference;
import com.sandvoxel.generitech.common.blocks.Blocks;
import com.sandvoxel.generitech.common.config.ConfigWorldGen;
import com.sandvoxel.generitech.common.config.ConfigWorldGen.OreConfig;
import com.sandvoxel.generitech.api.util.EnumOreType;
import com.sandvoxel.generitech.common.util.EnumOres;
import com.sandvoxel.generitech.common.util.LogHelper;
import com.sandvoxel.generitech.common.util.WorldInfoHelper;
import net.minecraft.block.Block;
import net.minecraft.block.state.IBlockState;
import net.minecraft.block.state.pattern.BlockMatcher;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.ChunkCoordIntPair;
import net.minecraft.world.World;
import net.minecraft.world.chunk.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraftforge.event.world.ChunkDataEvent;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.TickEvent;
import net.minecraftforge.fml.relauncher.Side;

import java.util.*;

public class WorldGen implements IWorldGenerator {
    private static List<OreGen> oreSpawnList = new ArrayList<>();
    private static ArrayListMultimap retrogenChunks = ArrayListMultimap.create();
    private int numChunks = 2;
    private static boolean retrogenEnabled = true;
    private static LinkedList<WorldGen> worlds = new LinkedList<>();
    private static HashMap<String, NBTTagCompound> loadedChunks = new HashMap<>();


    public WorldGen() {
        worlds.add(this);
    }

    public static void init() {
        for (EnumOres ore : EnumOres.byType(EnumOreType.ORE)) {
            // Always add ores, in case they get enabled at runtime
            OreConfig config = ConfigWorldGen.OreGenConfig.get(ore);
            WorldGen.addOreGen(ore.getName(), Blocks.BLOCK_ORE.getBlock().getStateFromMeta(ore.getMeta()), config);
        }
    }

    public static OreGen addOreGen(String name, IBlockState block, OreConfig oreConfig) {
        OreGen oreGen = new OreGen(name, block, net.minecraft.init.Blocks.stone, oreConfig);
        oreSpawnList.add(oreGen);
        return oreGen;
    }

    public void genOres(Random rand, int chunkX, int chunkZ, World world) {
        for (OreGen oreGen : oreSpawnList) {
            oreGen.generate(world, rand, chunkX * 16, chunkZ * 16);
        }
    }

    public void regenOres(Random rand, ChunkCoordIntPair chunkCoordIntPair, World world) {
        for (OreGen oreGen : oreSpawnList) {
            if (loadedChunks.get(chunkCoordIntPair.toString()).getBoolean(oreGen.name)) {
                oreGen.generate(world, rand, chunkCoordIntPair.chunkXPos * 16, chunkCoordIntPair.chunkZPos * 16);
            }
        }
        saveOreGenInfo(loadedChunks.get(chunkCoordIntPair.toString()));
    }

    private static boolean isRetrogenEnabled() {
        return retrogenEnabled;
    }

    public static void setRetrogenEnabled(boolean enabled)
    {
        retrogenEnabled = enabled;
    }

    public static boolean isRetroGenRequired(NBTTagCompound tagCompound)
    {
        boolean required = false;
        for (OreGen oreGen : oreSpawnList)
        {
            required = (tagCompound.getBoolean(oreGen.name) && (oreGen.oreConfig.Enabled));
        }

        return required;
    }

    private void saveOreGenInfo(NBTTagCompound tagCompound)
    {
        for (OreGen oreGen : oreSpawnList)
        {
            tagCompound.setBoolean(oreGen.name, oreGen.oreConfig.Enabled);
        }
    }

    public static void markChunksForRegen(){
        for (Object obj : loadedChunks.entrySet()) {
            Map.Entry pair = (Map.Entry) obj;
            NBTTagCompound tagCompound = (NBTTagCompound) pair.getValue();
            if (isRetroGenRequired((NBTTagCompound) pair.getValue())) {
                LogHelper.info(String.format("Chunk %s has been flagged for Ore RetroGen by %s", pair.getKey(), Reference.MOD_NAME));
                retrogenChunks.put(tagCompound.getInteger("DimID"), pair.getValue());
            }
        }
    }

    @SubscribeEvent
    public void chunkSave(ChunkDataEvent.Save event)
    {
        ChunkCoordIntPair coordIntPair = event.getChunk().getChunkCoordIntPair();
        NBTTagCompound tagCompound = new NBTTagCompound();
        event.getData().setTag(Reference.MOD_ID, tagCompound);

        if (loadedChunks.containsKey(coordIntPair.toString())) {
            for (OreGen oreGen : oreSpawnList) {
                tagCompound.setBoolean(oreGen.name, loadedChunks.get(coordIntPair.toString()).getBoolean(oreGen.name));
            }
        }
        else
        {
            LogHelper.debug("Chunk" + coordIntPair.toString() + "not loaded?");
        }
    }

    @SubscribeEvent
    public void chunkLoad(ChunkDataEvent.Load event)
    {
        int dimID = event.getWorld().provider.getDimension();
        NBTTagCompound tag = event.getData().getCompoundTag(Reference.MOD_ID);
        ChunkCoordIntPair coordIntPair = event.getChunk().getChunkCoordIntPair();
        loadedChunks.put(coordIntPair.toString(),tag);
        tag.setInteger("DimID",dimID);

        if(!isRetrogenEnabled())
            return;

        NBTTagCompound tagCompound = event.getData().getCompoundTag(Reference.MOD_ID);
        if(isRetroGenRequired(tagCompound))
        {
            LogHelper.info(String.format("Chunk %s has been flagged for Ore RetroGen by %s", event.getChunk().getChunkCoordIntPair(), Reference.MOD_NAME));
            retrogenChunks.put(dimID, event.getChunk().getChunkCoordIntPair());
        }
    }

    @SubscribeEvent
    public void chunkUnload(ChunkDataEvent.Unload event) {
        loadedChunks.remove(event.getChunk().getChunkCoordIntPair().toString());
    }

    @SubscribeEvent
    public void serverWorldTick(TickEvent.WorldTickEvent event)
    {
        if(event.side == Side.CLIENT || event.phase == TickEvent.Phase.START)
            return;

        int dimID = event.world.provider.getDimension();
        int counter = 0;

        List<ChunkCoordIntPair> chunks = retrogenChunks.get(dimID);

        if(chunks != null && !chunks.isEmpty())
        {
            if(WorldInfoHelper.getTps() >= 20)
            {
                numChunks++;
            }
            else
            {
                numChunks = Math.max(2, numChunks - 1);
            }

            for (int i = 1; i < numChunks; i++)
            {
                int index = chunks.size() - i;
                if(index < 0)
                    return;

                counter++;

                ChunkCoordIntPair coordIntPair = chunks.get(index);

                long worldSeed = event.world.getSeed();
                Random fmlRand = new Random(worldSeed);
                long xSeed = fmlRand.nextLong() >> 3;
                long zSeed = fmlRand.nextLong() >> 3;

                fmlRand.setSeed(xSeed * coordIntPair.chunkXPos + zSeed * coordIntPair.chunkZPos ^ worldSeed);
                regenOres(fmlRand, chunks.get(index), event.world);

                chunks.remove(index);
            }

            if (counter > 0)
                LogHelper.info(String.format("Retrogen was performed on %s chunks. %s chunks remaining", counter, Math.max(0, chunks.size())));
        }
    }

    @Override
    public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator chunkGenerator, IChunkProvider chunkProvider) {
        genOres(random, chunkX, chunkZ, world);
    }


    public static class OreGen
    {
        String name;
        WorldGenMinableCustom worldGenMinable;
        OreConfig oreConfig;

        public OreGen(String name, IBlockState state, Block replaceTarget, OreConfig config)
        {
            this.name = name;
            this.worldGenMinable = new WorldGenMinableCustom(state, config.MinVeinSize, config.MaxVeinSize, BlockMatcher.forBlock(replaceTarget));
            this.oreConfig = config;
        }

        public void generate(World world, Random random, int x, int z)
        {
            if(oreConfig.Enabled && oreConfig.isEnabledForDim(world.provider.getDimension()))
            {
                for(int i = 0; i < oreConfig.ChunkOccurrence; i++)
                {
                    if(random.nextInt(100) < oreConfig.Weight)
                    {
                        BlockPos blockPos = new BlockPos(x + random.nextInt(16), oreConfig.MinY + random.nextInt(oreConfig.MaxY - oreConfig.MinY), z + random.nextInt(16));
                        this.worldGenMinable.generate(world, random, blockPos);
                    }
                }
            }
        }
    }
}
